### ISSUE TITLE
/src and /dist not synchronised in v0.2.5

### ISSUE THREAD

**Issue by ibmjm** [kgrandemange/vue-flip#11]
## Problem
I tried using VueFlip with the`bindWithMe` prop, so that I can control flipping (using buttons on my front and back of the card).  It isn't working.

## Troubleshooting
Unfortunately, the /dist folder is not up to date with the /src and thus it's missing the Watcher on the `bindWithMe` prop.

## Solution
I think it's as simple as someone rebuilding the /dist folder and pushing out a new version (0.2.6?)...

**Comment by kgrandemange** [comment]
Ok, it's my fault, I merged a PR when I was on vacation and it's not a good idea ...
Thx for the report.

**Comment by kgrandemange** [comment]
Ok it's fixed with 0.3.0 version.

**Comment by ibmjm** [comment]
Thanks @kgrandemange 
I upgraded to 0.3.0 and can confirm it is working now.  I really appreciate this component and how quickly you responded to resolve the problem.  +1

**Comment by kgrandemange** [comment]
Thank you! :smile_cat:
