### ISSUE TITLE
repair readme

### ISSUE THREAD

**Issue by realmx** [kgrandemange/vue-flip#12]
## before 

|               | Description             | Type    | Default Value |
| ------------- | ----------------------- | ------- | ------------- |
| active-click  | flip on click           | Boolean | False         |
| active-hover  | flip on hover           | Boolean | False         |
| height        | coponent height         | String  |               |
| width         | component with          | String  |               |
| transition    | component transition    | String  | 0.5s          |
| bindWithMe    | bind flip with variable | Boolean |               |

## after

|              | Description             | Type    | Required | Default Value |
| ------------ | ----------------------- | ------- | -------- | ------------- |
| active-click | flip on click           | Boolean | False    | False         |
| active-hover | flip on hover           | Boolean | False    | False         |
| height       | component height        | String  | False    |               |
| width        | component width         | String  | True     |               |
| transition   | component transition    | String  | False    | 0.5s          |
| bindWithMe   | bind flip with variable | Boolean | False    |               |

**Comment by kgrandemange** [comment]
Indeed with Required column it's clearer.

**Comment by kgrandemange** [comment]
It's done.
