### ISSUE TITLE
Height problem

### ISSUE THREAD

**Issue by pbakiewicz** [kgrandemange/vue-flip#14]
Is there a way to set height="100%" and it will adjust to the heightest slot?

**Comment by kgrandemange** [comment]
Hello @pbakiewicz,

Maybe you want something like this:

https://codesandbox.io/s/vue-template-z499t?fontsize=14

Otherwise can you write a codesanbox example?

**Comment by GunnarPDX** [comment]
If you set the height and width props to: height="inherit" width="inherit" you can manage those from a CSS class like you would with any other div, just assign a class to the vue-flip and put your height settings in there.
