### ISSUE TITLE
`v-model` not respected for initial state

### ISSUE THREAD

**Issue by fjeddy** [kgrandemange/vue-flip#23]
```
<template>
  <vue-flip width="100" height="91" v-model="cardFlipped">
    <template v-slot:front>
      <img :src="'/images/cards/front.png'" />
    </template>
    <template v-slot:back>
      <img :src="'/images/cards/back.png'" />
    </template>
  </vue-flip>
</template>

<script>
export default {
  computed: {
    cardFlipped() {
      return true;
    }
  }
}
</script>
```

On initial load, then this will show the wrong sides. Instead of showing the back, like it should, then it's showing the front.

You have to change the content of the v-model after initial load for the correct side of the card to show, even tho v-model is always set to true.

**Comment by kgrandemange** [comment]
@fjeddy thank you for the report. This is a case that I missed 😲.
Fixed it in 1.0.2 version.

[Démo](https://codesandbox.io/s/beautiful-thompson-9ylku?file=/src/App.vue)
