### ISSUE TITLE
Can you flip it horizontal?

### ISSUE THREAD

**Issue by slayer3600** [kgrandemange/vue-flip#27]
Would it be possible to add support for flipping horizontally (on rotateX instead of rotateY I assume)?

**Comment by kgrandemange** [comment]
Hello @slayer3600 ,

It's a really good idea, i will implement this feature.

**Comment by kgrandemange** [comment]
Hi @slayer3600,

Horizontal support was added in version 2.2.0. Thanks for the idea.

**Comment by anhcunmio** [comment]
@kgrandemange , Thanks for the amazing library, but the horizontal flip is not working properly. I try to add the Horizontal prop to component but when flipped the back side disappeared

**Comment by kgrandemange** [comment]
Can you share an example? In the example provided in the documentation, it works.
