### ISSUE TITLE
disable click on back

### ISSUE THREAD

**Issue by goranGG** [kgrandemange/vue-flip#3]
is there any way to disable click on slot="back"?
and manually flip it with a button outside vue-flip?

**Comment by kgrandemange** [comment]
ATM it's not possible.

**Comment by kgrandemange** [comment]
At the time being, there is no proper way to revert a `vue-flip` by positioning a button outside of it. For now, the only way is to remove the `hover` class manually.

**Comment by goranGG** [comment]
OK, I made workaround
made container(width 100% height 100%) and set it to doNothing
but on back I set ref, and in vueJS just called click to ref

**Comment by kgrandemange** [comment]
A better way to do it is:

(Example from [here](https://vue-flip.kevingrandemange.net/))

```vue
<template>
    <vue-flip :active-click="activeOnClick" class="simple-test" width="20%" height="50px">
        <template slot="front">
            <div style="display:flex; align-items: center; justify-content: center; height:100%; width:100%" @click="handleClick">disable me!</div>
        </template>
        <div slot="back">test back</div>
    </vue-flip>
</template>
<script>
    data () {
        return {
            activeOnClick: true
        }
    },
    methods: {
        handleClick () {
            this.activeOnClick = false
        }
    }
</script>
```
