### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by lhoucinecherif** [kgrandemange/vue-flip#32]
Hi, I have some issue rendering components having vue-flip (a using gridesome),  I can solve the issue wrapping the components inside <ClientOnly>, but it doesn't generate the html/text content (for seo purpose ) inside the module when pages are  built!

**Comment by iampapagray** [comment]
How do you add this library to a nuxt app

**Comment by kgrandemange** [comment]
Now it's working on Nuxt 3.
