### ISSUE TITLE
Vue 2 Typescript Support

### ISSUE THREAD

**Issue by deen13** [kgrandemange/vue-flip#33]
Hey man, 

It would be nice if the types would also be available for the 'legay' vue 2 build. Although the version 3 of vue might be stable I think version 2 is the most common since the eco-system is not ready yet. Nuxt and vuetify for example have not released a version that works with vue 3 yet.

**Comment by kgrandemange** [comment]
I wouldn't support vue 2 typescript support but anyone can do a PR.
