### ISSUE TITLE
Try to install into a NuxtJs project, but show both flip sides

### ISSUE THREAD

**Issue by amrigo** [kgrandemange/vue-flip#8]
I do install vue-flip into a NuxtJs (VueJS) project created using this command: npx create-nuxt-app <project-name>.

At index.vue file i just add:

```
<vue-flip active-click="true">
    <div slot="front">
        front
    </div>
    <div slot="back">
        back
    </div>
</vue-flip>
```

I do register the plugin at nuxt.config.js :

```
  plugins: [
    '~/plugins/vue-flip'
  ]
```
And create the file vue-flip.js at the plugins folder :

```
import Vue from 'vue'

import VueFlip from 'vue-flip'

Vue.use(VueFlip)
```

Also add the style:

```
.front {
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #673AB7;
      color: white;
    }

    .back {
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #FFC107;
      color: white
    }
```

After run the command line:  `npm run dev` and at localhost:3000 the text front and back are both visible, instead of showing just the front text, so when clicking the back text would appear.

Is there any additional step require to integrate with Nuxt Js?

**Comment by kgrandemange** [comment]
Hello @amrigo,

your issue is resolved?
I nerver try to add VueFlip in Nuxt.js but I can investigate your problem.

**Comment by iampapagray** [comment]
@kgrandemange Im trying to add this to a Nuxt.js app. After trying the above steps, i get an error (Object(...) is not a function).
Do you have any guides on adding this successfully to a Nuxt.js project?
